apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: test-pipeline
spec:
  workspaces:
    - name: shared-data
  tasks:
    - name: test-task
      workspaces:
        - name: shared-data
      taskSpec:
        workspaces:
          - name: shared-data
        steps:
          - name: test
            image: busybox
            script: echo "test"
