apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: test-run
spec:
  pipelineRef:
    name: test-pipeline
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
